services:
  backend:
    build:
      context: ../app
      dockerfile: ../docker/back/Dockerfile
    environment:
      - HOST=${HOST}
      - BACKEND_PORT=${BACKEND_PORT}
      - OPENSEARCH_HOST=${OPENSEARCH_HOST}
      - OPENSEARCH_PORT=${OPENSEARCH_PORT}
      - OPENSEARCH_USER=${OPENSEARCH_USER}
      - OPENSEARCH_PASSWORD=${OPENSEARCH_PASSWORD}
    env_file:
      - ../.env.example
    ports:
       - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ../app:/app
    networks:
      - app-network
    depends_on:
      - opensearch-node

  frontend:
    build:
      context: ../app
      dockerfile: ../docker/front/Dockerfile
    ports:
      - "${FRONTEND_PORT}:${VITE_PORT}"
    networks:
      - app-network
    volumes:
      - ../app:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend

  opensearch-node:
    image: opensearchproject/opensearch:2.11.1
    container_name: opensearch-node
    environment:
      - discovery.type=single-node
      - "DISABLE_SECURITY_PLUGIN=true"
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    networks:
      - app-network
    ports:
      - "${OPENSEARCH_PORT}:${OPENSEARCH_PORT}"
      - "${OPENSEARCH_UNUSED_PORT}:${OPENSEARCH_UNUSED_PORT}"

  seed:
    image: python:3.11
    container_name: seed
    volumes:
      - ./seed.py:/seed.py
    command: sh -c "pip install opensearch-py faker && python seed.py"
    networks:
      - app-network
    depends_on:
      - opensearch-node

volumes:
  opensearch-data:

networks:
  app-network:
