services:
  backend:
    build:
      context: ../app
      dockerfile: ../docker/back/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../app:/app
    networks:
      - app-network
    depends_on:
      - opensearch-node

  frontend:
    build:
      context: ../app
      dockerfile: ../docker/front/Dockerfile
    ports:
      - "3000:5173"
    networks:
      - app-network
    volumes:
      - ../app:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:8000
    depends_on:
      - backend

  opensearch-node:
    image: opensearchproject/opensearch:2.11.1
    container_name: opensearch-node
    environment:
      - discovery.type=single-node
      - "DISABLE_SECURITY_PLUGIN=true"
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    networks:
      - app-network
    ports:
      - "9200:9200"
      - "9600:9600"

volumes:
  opensearch-data:

networks:
  app-network:
